notifications:
  email: false

language: rust

# if pull request: always build
# if push: only build for master branch
if: (type != push) OR (type = push AND branch = master)

matrix:
  include:
    - os: osx
      osx_image: xcode10.3
    - os: windows

install:
  - cargo install --force cbindgen
  - if [[ $TRAVIS_OS_NAME == 'windows' ]]; then rustup default stable-i686-pc-windows-msvc; fi

script:
  - cmake --version
  - cmake -Bbuild
  - cmake --build build --config Release

cache: cargo
