notifications:
  email: false

language: rust

# if pull request: always build
# if push: only build for master branch
if: (type != push) OR (type = push AND branch = master)

matrix:
  include:
    - os: osx
      osx_image: xcode10.3
    - os: windows

install:
  - cargo install cbindgen
  - if [[ $TRAVIS_OS_NAME == 'windows' ]]; then rustup default stable-i686-pc-windows-msvc; fi

script:
  - echo "Testing Rust code..."
  - cd distortionlib
  - cargo test

  - echo "Building plugin..."
  - cd $TRAVIS_BUILD_DIR
  - cmake --version
  - cmake -Bbuild
  - cmake --build build --config Release

  - echo "SUCCESS"

cache: cargo
